version: '2'

services:
  mongodb:
    image: 'mongo:3.2'

  redis:
    image: 'redis:4'

  mail:
    image: 'mailhog/mailhog'
    ports:
      - '8025:8025'

  xapi:
    image: 'cshr/learning-locker-xapi'
    ports:
      - '8081:8081'
    env_file:
      - variables.env
    depends_on:
      - mongodb
      - redis

  api-server:
    image: 'cshr/learning-locker-api-server'
    ports:
      - '8080:8080'
    env_file:
      - variables.env
    depends_on:
      - mongodb
      - redis
      - mail

  api-worker:
    image: 'cshr/learning-locker-api-worker'
    env_file:
      - variables.env
    depends_on:
      - api-server

  ui:
    image: 'cshr/learning-locker-ui'
    env_file:
      - variables.env
    ports:
      - '3000:3000'
    depends_on:
      - api-server

  cli:
    image: 'cshr/learning-locker-cli'
    env_file:
      - variables.env
    depends_on:
      - api-server
    stdin_open: true
    tty: true
